name: docker publish
on:
  push:
    branches:
    - master
jobs:
  publish-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: suzutan/discord-youtube-notifier/discord-youtube-notifier
        username: suzutan
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
